# Generated by Django 5.2.3 on 2025-06-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="konto",
            name="typ",
            field=models.CharField(
                choices=[
                    ("BARMITTEL", "Barmittel (Kasse, Bank)"),
                    ("GIROKONTO", "Girokonto"),
                    ("FORDERUNGEN", "Forderungen"),
                    ("VERBINDLICHKEITEN", "Verbindlichkeiten"),
                    ("EINNAHMEN", "Einnahmen"),
                    ("AUSGABEN", "Ausgaben"),
                    ("PRIVAT", "Private Konten"),
                    ("ANLAGE", "Anlagevermögen"),
                    ("SONSTIGE", "Sonstige"),
                    ("REISEKOSTEN", "Reisekosten"),
                    ("IT-KOSTEN", "IT-Kosten"),
                    ("ABSCHREIBUNGEN", "Abschreibungen"),
                    ("BETRIEBSAUSGABEN", "Betriebsausgaben"),
                    ("UMSATZERLÖSE", "Umsatzerlöse"),
                    ("FAHRZEUGKOSTEN", "Fahrzeugkosten"),
                    ("WERBUNG & REPRÄSENTATION", "Werbung & Repräsentation"),
                    ("BÜRO & VERWALTUNG", "Büro & Verwaltung"),
                    ("RAUMKOSTEN", "Raumkosten"),
                    ("STEUERVERBINDLICHKEIT", "Steuerverbindlichkeit"),
                    ("STEUERVERRECHNUNG", "Steuerverrechnung"),
                    ("PRIVATKONTO", "Privatkonto"),
                    ("KORREKTURPOSTEN", "Korrekturposten"),
                ],
                help_text="Weitere Klassifizierung für bessere Übersicht",
                max_length=30,
                verbose_name="Kontotyp",
            ),
        ),
    ]
