# Generated by Django 5.2.3 on 2025-06-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konten", "0002_alter_konto_typ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="konto",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("AKTIVKONTO", "Aktivkonto (Vermögen)"),
                    ("PASSIVKONTO", "Passivkonto (Kapital/Schulden)"),
                    ("AUFWAND", "Aufwandskonto (Ausgaben)"),
                    ("ERTRAG", "Ertragskonto (Einnahmen)"),
                    ("EIGENKAPITAL", "Eigenkapital"),
                    ("ERLÖSE", "Erlöse"),
                    ("ANLAGEVERMÖGEN", "Anlagevermögen"),
                    ("UMLAUFVERMÖGEN", "Umlaufvermögen"),
                    ("VERBINDLICHKEITEN", "Verbindlichkeiten"),
                ],
                help_text="SKR03-Kategorie des Kontos",
                max_length=20,
                verbose_name="Kontokategorie",
            ),
        ),
        migrations.AlterField(
            model_name="konto",
            name="typ",
            field=models.CharField(
                choices=[
                    ("BARMITTEL", "Barmittel (Kasse, Bank)"),
                    ("GIROKONTO", "Girokonto"),
                    ("FORDERUNGEN", "Forderungen"),
                    ("VERBINDLICHKEITEN", "Verbindlichkeiten"),
                    ("EINNAHMEN", "Einnahmen"),
                    ("AUSGABEN", "Ausgaben"),
                    ("PRIVAT", "Private Konten"),
                    ("ANLAGE", "Anlagevermögen"),
                    ("SONSTIGE", "Sonstige"),
                    ("REISEKOSTEN", "Reisekosten"),
                    ("IT-KOSTEN", "IT-Kosten"),
                    ("ABSCHREIBUNGEN", "Abschreibungen"),
                    ("BETRIEBSAUSGABEN", "Betriebsausgaben"),
                    ("UMSATZERLÖSE", "Umsatzerlöse"),
                    ("FAHRZEUGKOSTEN", "Fahrzeugkosten"),
                    ("WERBUNG & REPRÄSENTATION", "Werbung & Repräsentation"),
                    ("BÜRO & VERWALTUNG", "Büro & Verwaltung"),
                    ("RAUMKOSTEN", "Raumkosten"),
                    ("STEUERVERBINDLICHKEIT", "Steuerverbindlichkeit"),
                    ("STEUERVERRECHNUNG", "Steuerverrechnung"),
                    ("PRIVATKONTO", "Privatkonto"),
                    ("KORREKTURPOSTEN", "Korrekturposten"),
                    ("SACHANLAGEN", "Sachanlagen"),
                    ("STEUERFORDERUNG", "Steuerforderung"),
                    ("PERSONALKOSTEN", "Personalkosten"),
                    ("ENTNAHMEN", "Entnahmen"),
                ],
                help_text="Weitere Klassifizierung für bessere Übersicht",
                max_length=30,
                verbose_name="Kontotyp",
            ),
        ),
    ]
