# Generated by Django 5.2.4 on 2025-07-07 07:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "__first__"),
        ("customers", "__first__"),
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="customers.customer",
                verbose_name="Kunde",
            ),
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-invoice_date", "-invoice_number"],
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
            },
        ),
        migrations.AlterModelOptions(
            name="invoiceposition",
            options={
                "ordering": ["pos"],
                "verbose_name": "Rechnungsposition",
                "verbose_name_plural": "Rechnungspositionen",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="customers.company",
                verbose_name="Unternehmen",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="einvoice_xml_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="E-Invoice XML Pfad"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent",
            field=models.BooleanField(default=False, verbose_name="E-Mail versendet"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="E-Mail Versanddatum"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="footer_text",
            field=models.TextField(
                blank=True,
                help_text="Zusätzlicher Text am Ende der Rechnung",
                null=True,
                verbose_name="Fußtext",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_einvoice",
            field=models.BooleanField(default=False, verbose_name="E-Invoice"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Bezahlter Betrag",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Zahlungsdatum"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="PDF Pfad"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="performance_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leistungsdatum (Legacy)"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Zwischensumme (Netto)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="MwSt-Betrag",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Geändert von",
            ),
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.catalogitem",
                verbose_name="Katalog-Artikel",
            ),
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Erstellt am",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Rabatt (%)",
            ),
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leer = Standard-MwSt-Satz verwenden",
                max_digits=5,
                null=True,
                verbose_name="MwSt-Satz (%)",
            ),
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
        ),
        migrations.AddField(
            model_name="invoiceposition",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Geändert von",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="baustellenadresse",
            field=models.CharField(
                help_text="Wird als Betreff in der Rechnung angezeigt",
                max_length=500,
                verbose_name="Baustellenadresse",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fälligkeitsdatum"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Rechnungsdatum"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Rechnungsnummer"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Einleitungstext für die Rechnung",
                null=True,
                verbose_name="Einleitungstext",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="performance_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leistungszeitraum bis"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="performance_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leistungszeitraum von"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("sent", "Versendet"),
                    ("paid", "Bezahlt"),
                    ("overdue", "Überfällig"),
                    ("cancelled", "Storniert"),
                    ("partial", "Teilweise bezahlt"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Gesamtbetrag (Brutto)",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
        ),
        migrations.AlterField(
            model_name="invoiceposition",
            name="description",
            field=models.CharField(max_length=500, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="invoiceposition",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="invoices.invoice",
                verbose_name="Rechnung",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceposition",
            name="pos",
            field=models.PositiveIntegerField(default=1, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="invoiceposition",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Menge",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceposition",
            name="unit",
            field=models.CharField(max_length=20, verbose_name="Einheit"),
        ),
        migrations.AlterField(
            model_name="invoiceposition",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Einzelpreis (Netto)",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
