# Generated by Django 5.0.14 on 2025-06-26 10:06

import belege.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beleg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Eindeutige ID des Belegs",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datei",
                    models.FileField(
                        help_text="Beleg-Datei (PDF, JPG, PNG, GIF)",
                        upload_to=belege.models.beleg_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png", "gif"]
                            )
                        ],
                        verbose_name="Datei",
                    ),
                ),
                (
                    "original_dateiname",
                    models.CharField(
                        help_text="Ursprünglicher Dateiname",
                        max_length=255,
                        verbose_name="Original-Dateiname",
                    ),
                ),
                (
                    "dateigröße",
                    models.PositiveIntegerField(
                        help_text="Dateigröße in Bytes", verbose_name="Dateigröße"
                    ),
                ),
                (
                    "beleg_typ",
                    models.CharField(
                        choices=[
                            ("RECHNUNG_EINGANG", "Eingangsrechnung"),
                            ("RECHNUNG_AUSGANG", "Ausgangsrechnung"),
                            ("QUITTUNG", "Quittung"),
                            ("BANKBELEG", "Bankbeleg"),
                            ("VERTRAG", "Vertrag"),
                            ("SONSTIGES", "Sonstiger Beleg"),
                        ],
                        default="SONSTIGES",
                        help_text="Art des Belegs",
                        max_length=20,
                        verbose_name="Beleg-Typ",
                    ),
                ),
                (
                    "rechnungsdatum",
                    models.DateField(
                        blank=True,
                        help_text="Datum der Rechnung/des Belegs",
                        null=True,
                        verbose_name="Rechnungsdatum",
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bruttobetrag des Belegs in Euro",
                        max_digits=10,
                        null=True,
                        verbose_name="Betrag",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEU", "Neu (unbearbeitet)"),
                            ("GEPRUEFT", "Geprüft"),
                            ("VERBUCHT", "Verbucht"),
                            ("ARCHIVIERT", "Archiviert"),
                            ("FEHLER", "Fehlerhaft"),
                        ],
                        default="NEU",
                        help_text="Bearbeitungsstatus des Belegs",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Extrahierter Text durch OCR",
                        verbose_name="OCR-Text",
                    ),
                ),
                (
                    "ocr_verarbeitet",
                    models.BooleanField(
                        default=False,
                        help_text="Wurde OCR bereits durchgeführt?",
                        verbose_name="OCR verarbeitet",
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(
                        blank=True,
                        help_text="Kurze Beschreibung des Belegs",
                        max_length=200,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "notizen",
                    models.TextField(
                        blank=True,
                        help_text="Interne Notizen zum Beleg",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "hochgeladen_am",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                (
                    "geaendert_am",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
            ],
            options={
                "verbose_name": "Beleg",
                "verbose_name_plural": "Belege",
                "ordering": ["-rechnungsdatum", "-hochgeladen_am"],
            },
        ),
    ]
