# Generated by Django 5.0.14 on 2025-06-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("belege", "0001_initial"),
        ("buchungen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="geschaeftspartner",
            field=models.ForeignKey(
                blank=True,
                help_text="Zugehöriger Geschäftspartner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="belege",
                to="buchungen.geschaeftspartner",
                verbose_name="Geschäftspartner",
            ),
        ),
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(
                fields=["rechnungsdatum"], name="belege_bele_rechnun_111508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(
                fields=["beleg_typ"], name="belege_bele_beleg_t_16b834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(fields=["status"], name="belege_bele_status_36f9cb_idx"),
        ),
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(
                fields=["geschaeftspartner"], name="belege_bele_geschae_1f05e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="beleg",
            index=models.Index(fields=["betrag"], name="belege_bele_betrag_d55149_idx"),
        ),
    ]
