# Generated by Django 5.2.3 on 2025-06-26 14:54

import django.core.validators
from django.db import migrations, models

import belege.models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="rechnungsnummer",
            field=models.CharField(
                blank=True,
                help_text="Rechnungsnummer aus dem Beleg extrahiert",
                max_length=50,
                verbose_name="Rechnungsnummer",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="datei",
            field=models.FileField(
                help_text="Beleg-Datei (PDF, JPG, PNG, GIF)",
                upload_to=belege.models.generiere_intelligenten_dateinamen,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="Datei",
            ),
        ),
    ]
