# Generated by Django 5.2.3 on 2025-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0003_beleg_rechnungsnummer_alter_beleg_datei"),
    ]

    operations = [
        migrations.CreateModel(
            name="BelegKategorieML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schluesselwoerter",
                    models.TextField(
                        help_text="Erkannte Schlüsselwörter aus dem Beleg (JSON)",
                        verbose_name="Schlüsselwörter",
                    ),
                ),
                (
                    "lieferant_name",
                    models.CharField(
                        help_text="Erkannter Lieferantenname",
                        max_length=200,
                        verbose_name="Lieferant",
                    ),
                ),
                (
                    "betrag_bereich",
                    models.CharField(
                        help_text="Betragsbereich (0-50, 50-200, 200-1000, 1000+)",
                        max_length=20,
                        verbose_name="Betragsbereich",
                    ),
                ),
                (
                    "korrekte_kategorie",
                    models.CharField(
                        help_text="Korrekte Kategorie für das Training",
                        max_length=50,
                        verbose_name="Korrekte Kategorie",
                    ),
                ),
                (
                    "ist_einnahme",
                    models.BooleanField(
                        help_text="Ist es eine Einnahme (True) oder Ausgabe (False)?",
                        verbose_name="Ist Einnahme",
                    ),
                ),
                (
                    "vertrauen",
                    models.FloatField(
                        default=0.0,
                        help_text="Vertrauen der automatischen Kategorisierung (0-1)",
                        verbose_name="Vertrauen",
                    ),
                ),
                (
                    "trainiert_am",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Trainiert am"
                    ),
                ),
                (
                    "benutzer_korrektur",
                    models.BooleanField(
                        default=False,
                        help_text="Wurde von Benutzer korrigiert?",
                        verbose_name="Benutzer-Korrektur",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML-Kategorisierung",
                "verbose_name_plural": "ML-Kategorisierungen",
                "ordering": ["-trainiert_am"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="benutzer_bestaetigt",
            field=models.BooleanField(
                default=False,
                help_text="Hat der Benutzer die Kategorisierung bestätigt?",
                verbose_name="Benutzer bestätigt",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="ist_einnahme",
            field=models.BooleanField(
                blank=True,
                help_text="Vom Benutzer beim Upload als Einnahme/Ausgabe markiert",
                null=True,
                verbose_name="Ist Einnahme",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="ki_vertrauen",
            field=models.FloatField(
                default=0.0,
                help_text="Vertrauen der automatischen Kategorisierung (0-1)",
                verbose_name="KI-Vertrauen",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="ki_vorschlag",
            field=models.CharField(
                blank=True,
                help_text="KI-Vorschlag für Beleg-Typ",
                max_length=20,
                verbose_name="KI-Vorschlag",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="beleg_typ",
            field=models.CharField(
                choices=[
                    ("RECHNUNG_AUSGANG", "Ausgangsrechnung (Einnahme)"),
                    ("SONSTIGE_EINNAHME", "Sonstige Einnahme"),
                    ("RECHNUNG_EINGANG", "Eingangsrechnung (Ausgabe)"),
                    ("QUITTUNG", "Quittung (Ausgabe)"),
                    ("BANKBELEG", "Bankbeleg"),
                    ("BETRIEBSAUSGABE", "Betriebsausgabe"),
                    ("REISEKOSTEN", "Reisekosten"),
                    ("BÜROMATERIAL", "Büromaterial"),
                    ("MARKETING", "Marketing/Werbung"),
                    ("WEITERBILDUNG", "Weiterbildung"),
                    ("VERSICHERUNG", "Versicherung"),
                    ("MIETE", "Miete/Nebenkosten"),
                    ("VERTRAG", "Vertrag"),
                    ("SONSTIGES", "Sonstiger Beleg"),
                ],
                default="SONSTIGES",
                help_text="Art des Belegs",
                max_length=20,
                verbose_name="Beleg-Typ",
            ),
        ),
    ]
