# Generated by Django 5.2.4 on 2025-07-07 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogcategory",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_categories",
                to="customers.company",
                verbose_name="Unternehmen",
            ),
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="catalog.catalogcategory",
                verbose_name="Übergeordnete Kategorie",
            ),
        ),
        migrations.AddField(
            model_name="catalogcategory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Geändert von",
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="catalog.catalogcategory",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to="customers.company",
                verbose_name="Unternehmen",
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Erstellt von",
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Geändert von",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="catalog_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="catalog.catalogitem",
                verbose_name="Katalog-Eintrag",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Geändert von",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="catalogcategory",
            unique_together={("company", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="catalogitem",
            unique_together={("company", "item_number")},
        ),
    ]
