# Generated by Django 5.2.3 on 2025-06-26 16:51

import django.core.validators
import django.db.models.deletion
import dokumente.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DokumentKategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name der Kategorie",
                        max_length=100,
                        unique=True,
                        verbose_name="Kategorie-Name",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        blank=True,
                        help_text="Beschreibung der Kategorie",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "farbe",
                    models.CharField(
                        default="#6b7280",
                        help_text="Farbe für die Anzeige (Hex-Code)",
                        max_length=7,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "sortierung",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sortierreihenfolge",
                        verbose_name="Sortierung",
                    ),
                ),
                (
                    "aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Ist die Kategorie aktiv?",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "geändert_am",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
            ],
            options={
                "verbose_name": "Dokument-Kategorie",
                "verbose_name_plural": "Dokument-Kategorien",
                "ordering": ["sortierung", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dokument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Eindeutige ID des Dokuments",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "datei",
                    models.FileField(
                        help_text="Dokument-Datei (PDF, Bilder, Word, Text)",
                        upload_to=dokumente.models.generiere_dokumenten_dateinamen,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "doc",
                                    "docx",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="Datei",
                    ),
                ),
                (
                    "original_dateiname",
                    models.CharField(
                        help_text="Ursprünglicher Dateiname",
                        max_length=255,
                        verbose_name="Original-Dateiname",
                    ),
                ),
                (
                    "dateigröße",
                    models.PositiveIntegerField(
                        help_text="Dateigröße in Bytes", verbose_name="Dateigröße"
                    ),
                ),
                (
                    "titel",
                    models.CharField(
                        help_text="Titel/Betreff des Dokuments",
                        max_length=200,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("FINANZAMT", "💼 Finanzamt"),
                            ("KSK", "🎨 Künstlersozialkasse"),
                            ("VERSICHERUNG", "🛡️ Versicherung"),
                            ("VERTRAG", "📋 Vertrag"),
                            ("KORRESPONDENZ", "✉️ Korrespondenz"),
                            ("BEHÖRDE", "🏛️ Behörde"),
                            ("BANK", "🏦 Bank"),
                            ("STEUERBERATER", "📊 Steuerberater"),
                            ("RECHTLICHES", "⚖️ Rechtliches"),
                            ("SONSTIGES", "📄 Sonstiges"),
                        ],
                        default="SONSTIGES",
                        help_text="Kategorie des Dokuments",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        blank=True,
                        help_text="Organisation/Absender (z.B. Finanzamt München)",
                        max_length=200,
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True,
                        help_text="Datum des Dokuments",
                        null=True,
                        verbose_name="Dokument-Datum",
                    ),
                ),
                (
                    "aktenzeichen",
                    models.CharField(
                        blank=True,
                        help_text="Aktenzeichen oder Referenz",
                        max_length=100,
                        verbose_name="Aktenzeichen",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        blank=True,
                        help_text="Kurze Beschreibung des Inhalts",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "notizen",
                    models.TextField(
                        blank=True,
                        help_text="Persönliche Notizen und Kommentare",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEU", "🆕 Neu"),
                            ("BEARBEITUNG", "⏳ In Bearbeitung"),
                            ("ERLEDIGT", "✅ Erledigt"),
                            ("ARCHIVIERT", "📦 Archiviert"),
                            ("WICHTIG", "⚠️ Wichtig"),
                        ],
                        default="NEU",
                        help_text="Bearbeitungsstatus",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fälligkeitsdatum",
                    models.DateField(
                        blank=True,
                        help_text="Fälligkeits- oder Erinnerungsdatum",
                        null=True,
                        verbose_name="Fälligkeitsdatum",
                    ),
                ),
                (
                    "erinnerung_tage_vorher",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Erinnerung X Tage vor Fälligkeit",
                        verbose_name="Erinnerung (Tage vorher)",
                    ),
                ),
                (
                    "ocr_text",
                    models.TextField(
                        blank=True,
                        help_text="Extrahierter Text aus OCR",
                        verbose_name="OCR-Text",
                    ),
                ),
                (
                    "ki_analyse",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="KI-Analyse-Ergebnisse",
                        verbose_name="KI-Analyse",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags getrennt durch Kommas",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "geändert_am",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "verknüpfte_dokumente",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Verknüpfte Dokumente",
                        to="dokumente.dokument",
                        verbose_name="Verknüpfte Dokumente",
                    ),
                ),
                (
                    "kategorie_detail",
                    models.ForeignKey(
                        blank=True,
                        help_text="Detaillierte Kategorie",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dokumente.dokumentkategorie",
                        verbose_name="Detail-Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
                "ordering": ["-datum", "-erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="DokumentAktion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aktion",
                    models.CharField(
                        choices=[
                            ("ERSTELLT", "📝 Erstellt"),
                            ("BEARBEITET", "✏️ Bearbeitet"),
                            ("STATUS_GEÄNDERT", "🔄 Status geändert"),
                            ("KOMMENTAR", "💬 Kommentar hinzugefügt"),
                            ("DATEI_ERSETZT", "🔄 Datei ersetzt"),
                            ("VERKNÜPFT", "🔗 Verknüpft"),
                            ("ARCHIVIERT", "📦 Archiviert"),
                        ],
                        max_length=20,
                        verbose_name="Aktion",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        help_text="Beschreibung der durchgeführten Aktion",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "notizen",
                    models.TextField(
                        blank=True,
                        help_text="Zusätzliche Notizen",
                        verbose_name="Notizen",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "dokument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aktionen",
                        to="dokumente.dokument",
                        verbose_name="Dokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument-Aktion",
                "verbose_name_plural": "Dokument-Aktionen",
                "ordering": ["-erstellt_am"],
            },
        ),
        migrations.AddIndex(
            model_name="dokument",
            index=models.Index(
                fields=["kategorie"], name="dokumente_d_kategor_008d04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dokument",
            index=models.Index(fields=["status"], name="dokumente_d_status_478c4b_idx"),
        ),
        migrations.AddIndex(
            model_name="dokument",
            index=models.Index(fields=["datum"], name="dokumente_d_datum_cd353d_idx"),
        ),
        migrations.AddIndex(
            model_name="dokument",
            index=models.Index(
                fields=["organisation"], name="dokumente_d_organis_268fee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dokument",
            index=models.Index(
                fields=["fälligkeitsdatum"], name="dokumente_d_fälligk_bf54d4_idx"
            ),
        ),
    ]
