# Generated by Django 5.2.3 on 2025-06-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokumente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokument",
            name="dateigröße",
            field=models.PositiveIntegerField(
                default=0, help_text="Dateigröße in Bytes", verbose_name="Dateigröße"
            ),
        ),
    ]
