# Generated by Django 5.2.3 on 2025-06-28 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnChallenge",
            fields=[
                (
                    "challenge_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Challenge ID",
                    ),
                ),
                (
                    "challenge",
                    models.TextField(
                        help_text="Base64-kodierte Challenge für WebAuthn",
                        verbose_name="Challenge-Daten",
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("registration", "Registrierung"),
                            ("authentication", "Anmeldung"),
                        ],
                        max_length=20,
                        verbose_name="Challenge-Typ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Challenge läuft automatisch ab",
                        verbose_name="Läuft ab am",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Benutzer für diese Challenge (null bei Registrierung)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebAuthn-Challenge",
                "verbose_name_plural": "WebAuthn-Challenges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.TextField(
                        help_text="Eindeutige ID des WebAuthn-Credentials",
                        unique=True,
                        verbose_name="Credential ID",
                    ),
                ),
                (
                    "public_key",
                    models.TextField(
                        help_text="Der öffentliche Schlüssel des FIDO2-Geräts",
                        verbose_name="Öffentlicher Schlüssel",
                    ),
                ),
                (
                    "sign_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Zähler für Replay-Angriff-Schutz",
                        verbose_name="Signatur-Zähler",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="FIDO2-Schlüssel",
                        help_text="Benutzerfreundlicher Name für das FIDO2-Gerät",
                        max_length=100,
                        verbose_name="Gerätename",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt verwendet"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Ob dieser FIDO2-Schlüssel verwendet werden kann",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webauthn_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebAuthn-Credential",
                "verbose_name_plural": "WebAuthn-Credentials",
                "ordering": ["-created_at"],
            },
        ),
    ]
