# Generated by Django 5.2.3 on 2025-06-26 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Benutzerprofil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vorname",
                    models.CharField(
                        help_text="Ihr Vorname wie im Personalausweis",
                        max_length=100,
                        verbose_name="Vorname",
                    ),
                ),
                (
                    "nachname",
                    models.CharField(
                        help_text="Ihr Nachname wie im Personalausweis",
                        max_length=100,
                        verbose_name="Nachname",
                    ),
                ),
                (
                    "geburtsdatum",
                    models.DateField(
                        blank=True,
                        help_text="Format: TT.MM.JJJJ",
                        null=True,
                        verbose_name="Geburtsdatum",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Ihre Haupt-E-Mail-Adresse",
                        max_length=254,
                        verbose_name="E-Mail-Adresse",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True,
                        help_text="Ihre Telefonnummer (z.B. +49 123 456789)",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefonnummer muss im Format '+49...' oder '0...' eingegeben werden.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefonnummer",
                    ),
                ),
                (
                    "strasse",
                    models.CharField(
                        help_text="z.B. Musterstraße 123",
                        max_length=200,
                        verbose_name="Straße und Hausnummer",
                    ),
                ),
                (
                    "plz",
                    models.CharField(
                        help_text="5-stellige deutsche PLZ",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="PLZ muss 5 Ziffern haben (z.B. 12345)",
                                regex="^\\d{5}$",
                            )
                        ],
                        verbose_name="Postleitzahl",
                    ),
                ),
                (
                    "ort",
                    models.CharField(
                        help_text="Ihr Wohnort", max_length=100, verbose_name="Ort"
                    ),
                ),
                (
                    "steuer_id",
                    models.CharField(
                        help_text="11-stellige Steuer-ID (z.B. 12345678901)",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Steuer-ID muss genau 11 Ziffern haben",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="Steuer-Identifikationsnummer",
                    ),
                ),
                (
                    "wirtschaftsid",
                    models.CharField(
                        blank=True,
                        help_text="Wirtschafts-ID für Unternehmer (optional)",
                        max_length=15,
                        verbose_name="Wirtschafts-Identifikationsnummer",
                    ),
                ),
                (
                    "steuernummer",
                    models.CharField(
                        blank=True,
                        help_text="Ihre Steuernummer beim zuständigen Finanzamt",
                        max_length=20,
                        verbose_name="Steuernummer",
                    ),
                ),
                (
                    "finanzamt",
                    models.CharField(
                        blank=True,
                        help_text="Name und Ort Ihres Finanzamts",
                        max_length=200,
                        verbose_name="Zuständiges Finanzamt",
                    ),
                ),
                (
                    "umsatzsteuer_id",
                    models.CharField(
                        blank=True,
                        help_text="USt-IdNr. (nur bei Umsatzsteuerpflicht)",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="USt-IdNr. muss Format 'DE123456789' haben",
                                regex="^DE\\d{9}$",
                            )
                        ],
                        verbose_name="Umsatzsteuer-Identifikationsnummer",
                    ),
                ),
                (
                    "beruf",
                    models.CharField(
                        help_text="Ihre Haupttätigkeit (z.B. Freischaffender Künstler)",
                        max_length=200,
                        verbose_name="Beruf/Tätigkeit",
                    ),
                ),
                (
                    "kleinunternehmer_19_ustg",
                    models.BooleanField(
                        default=True,
                        help_text="Sind Sie Kleinunternehmer nach §19 UStG? (Empfohlen: Ja)",
                        verbose_name="Kleinunternehmer nach §19 UStG",
                    ),
                ),
                (
                    "gewerbe_angemeldet",
                    models.BooleanField(
                        default=False,
                        help_text="Haben Sie ein Gewerbe angemeldet?",
                        verbose_name="Gewerbe angemeldet",
                    ),
                ),
                (
                    "gewerbeanmeldung_datum",
                    models.DateField(
                        blank=True,
                        help_text="Wann wurde das Gewerbe angemeldet?",
                        null=True,
                        verbose_name="Datum der Gewerbeanmeldung",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        help_text="Ihre Haupt-Geschäfts-IBAN",
                        max_length=34,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Deutsche IBAN muss Format 'DE12345678901234567890' haben",
                                regex="^DE\\d{20}$",
                            )
                        ],
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Name Ihrer Bank",
                        max_length=200,
                        verbose_name="Bank-Name",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "aktualisiert_am",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "ist_vollstaendig",
                    models.BooleanField(
                        default=False,
                        help_text="Sind alle Pflichtfelder ausgefüllt?",
                        verbose_name="Profil vollständig",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Verknüpfter Django-Benutzer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzerprofil",
                "verbose_name_plural": "Benutzerprofile",
                "db_table": "einstellungen_benutzerprofil",
            },
        ),
    ]
