# Generated by Django 5.2.3 on 2025-06-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0001_initial"),
        ("konten", "0003_alter_konto_kategorie_alter_konto_typ"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardKontierung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buchungstyp",
                    models.CharField(
                        choices=[
                            ("einnahme", "Einnahme"),
                            ("ausgabe", "Ausgabe"),
                            ("privatentnahme", "Privatentnahme"),
                            ("privateinlage", "Privateinlage"),
                        ],
                        help_text="Art der Buchung",
                        max_length=20,
                        verbose_name="Buchungstyp",
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(
                        blank=True,
                        help_text="Optionale Beschreibung für diese Kontierung",
                        max_length=200,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "ist_aktiv",
                    models.BooleanField(
                        default=True,
                        help_text="Ist diese Standard-Kontierung aktiv?",
                        verbose_name="Aktiv",
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("geaendert_am", models.DateTimeField(auto_now=True)),
                (
                    "benutzerprofil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_kontierungen",
                        to="einstellungen.benutzerprofil",
                        verbose_name="Benutzerprofil",
                    ),
                ),
                (
                    "haben_konto",
                    models.ForeignKey(
                        help_text="Konto welches im Haben gebucht wird",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_haben_buchungen",
                        to="konten.konto",
                        verbose_name="Standard Haben-Konto",
                    ),
                ),
                (
                    "soll_konto",
                    models.ForeignKey(
                        help_text="Konto welches im Soll gebucht wird",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_soll_buchungen",
                        to="konten.konto",
                        verbose_name="Standard Soll-Konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard-Kontierung",
                "verbose_name_plural": "Standard-Kontierungen",
                "ordering": ["buchungstyp"],
                "unique_together": {("benutzerprofil", "buchungstyp")},
            },
        ),
    ]
