# Generated by Django 5.2.3 on 2025-07-01 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0002_standardkontierung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benutzerprofil",
            name="steuer_id",
            field=models.CharField(
                blank=True,
                help_text="11-stellige Steuer-ID (z.B. 12345678901)",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Steuer-ID muss genau 11 Ziffern haben",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="Steuer-Identifikationsnummer",
            ),
        ),
    ]
